apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: web
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web
    spec:
      selector:
        matchLabels:
          app: web
      template:
        metadata:
          labels:
            app: web
        spec:
          containers:
            - name: web
              image: flask-sample:v1
              ports:
                - containerPort: 80
                  name: web