apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: deployments.apps
spec:
  definitionRef:
    name: deployments.apps
---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: ingresses.extensions
spec:
  definitionRef:
    name: ingresses.extensions 
---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: services
spec:
  definitionRef:
    name: services 
